name: Copy dist to artifacts branch

on:
  push:
    branches:
      - main  # Reemplaza "main" por la rama desde donde quieres activar el workflow.

jobs:
  copy-dist:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para empujar cambios a otra rama.

      # 2. Construye el proyecto (si es necesario)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Cambia la versión según tu proyecto.
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # 3. Copia el contenido de dist a la rama `artifacts`
      - name: Copy dist to artifacts branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Cambia a la rama de destino o créala si no existe
          git switch artifacts || git switch --create artifacts

          # Limpia la rama y copia los archivos de dist
          git rm -rf .  # Elimina archivos existentes
          cp -r dist/* .  # Copia el contenido de dist a la raíz

          # Agrega y confirma los cambios
          git add .
          git commit -m "Actualizar contenido de dist desde main"

          # Empuja los cambios a la rama artifacts
          git push origin artifacts
