name: Deploy to Artifacts Branch

on:
  push:
    branches:
      - main  # Ejecuta el workflow solo cuando hay un push en la rama main.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Asegura que se pueda trabajar con múltiples ramas.

      # 2. Crear la rama `artifacts` desde cero
      - name: Prepare artifacts branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Eliminar la rama artifacts si ya existe
          if git rev-parse --verify origin/artifacts > /dev/null 2>&1; then
            git push origin --delete artifacts
          fi

          # Crear la rama artifacts basada en main
          git checkout -b artifacts

      # 3. Limpiar todo excepto el directorio .git
      - name: Clean branch
        run: |
          rm -rf ./*
          rm -rf .[^.] .??* || true  # Borra archivos ocultos excepto .git

      # 4. Instalar dependencias y construir el proyecto
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ajusta según tu proyecto
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # 5. Mover los archivos de `dist` a la raíz de la rama
      - name: Move dist content
        run: |
          cp -r dist/* .
          rm -rf dist node_modules  # Limpiar dist y node_modules

          # Agregar y confirmar los cambios
          git add .
          git commit -m "Deploy artifacts from main"

      # 6. Empujar los cambios a la rama artifacts
      - name: Push to artifacts branch
        run: |
          git push origin artifacts --force
