name: Copy dist to artifacts branch

on:
  push:
    branches:
      - main  # Reemplaza "main" por la rama desde donde quieres activar el workflow.

jobs:
  copy-dist:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para empujar cambios a otra rama.

      # 2. Construye el proyecto (si es necesario)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Cambia la versión según tu proyecto.

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # 3. Verifica que dist existe antes de copiar
      - name: Check dist folder
        run: |
          if [ ! -d dist ]; then
            echo "Error: dist folder does not exist"
            exit 1
          fi

      # 4. Copia el contenido de dist a la rama `artifacts`
      - name: Copy dist to artifacts branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Cambia a la rama de destino o créala si no existe
          git switch artifacts || git switch --create artifacts

          # Elimina todo el contenido actual de la rama
          rm -rf ./*  # Borra todos los archivos del directorio de trabajo
          git rm -rf . || true  # Elimina archivos rastreados en Git si existen

          # Copia el contenido de dist
          cp -r dist/* .  # Copia el contenido de dist al directorio actual

          # Agrega y confirma los cambios
          git add .
          git commit -m "Actualizar contenido de dist desde main"

          # Empuja los cambios a la rama artifacts
          git push origin artifacts
